"""Constants for the Golf Dashboard integration."""
from __future__ import annotations

from dataclasses import dataclass
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    UnitOfLength,
    UnitOfSpeed,
    UnitOfTime,
    DEGREE,
    REVOLUTIONS_PER_MINUTE,
)

DOMAIN = "golf_dashboard"

DEFAULT_PORT = 2920
RECONNECT_INTERVAL = 10  # seconds

# SSDP Discovery
SSDP_ST = "urn:openlaunch:service:websocket:1"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_NAME = "name"
CONF_INSTALL_DASHBOARDS = "install_dashboards"
CONF_INSTALL_DASHBOARDS_AGAIN = "install_dashboards_again"

# Device info from SSDP
CONF_MANUFACTURER = "manufacturer"
CONF_MODEL = "model"
CONF_SERIAL = "serial"


@dataclass(frozen=True)
class GolfDashboardSensorEntityDescription(SensorEntityDescription):
    """Describes a Golf Dashboard sensor entity."""

    json_key: str | None = None
    message_type: str | None = None  # "shot" or "status"
    precision: int | None = None  # Number of decimal places (None = no rounding)
    value_offset: int = 0  # Add this to the raw value (e.g., +1 for 0-indexed counts)


# Shot Data Sensors (from "type": "shot" messages)
SHOT_SENSORS: tuple[GolfDashboardSensorEntityDescription, ...] = (
    GolfDashboardSensorEntityDescription(
        key="session_shot_count",
        name="Session Shot Count",
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:counter",
        json_key="shot_number",
        message_type="shot",
        value_offset=1,  # shot_number is 0-indexed, display as 1-indexed
    ),
    GolfDashboardSensorEntityDescription(
        key="last_shot_time",
        name="Last Shot",
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock-outline",
        json_key="_last_shot_timestamp",  # Special: set by coordinator
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="ball_speed",
        name="Ball Speed",
        native_unit_of_measurement=UnitOfSpeed.METERS_PER_SECOND,
        device_class=SensorDeviceClass.SPEED,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        json_key="ball_speed_meters_per_second",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="vertical_launch_angle",
        name="Vertical Launch Angle",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:angle-acute",
        json_key="vertical_launch_angle_degrees",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="horizontal_launch_angle",
        name="Horizontal Launch Angle",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:angle-acute",
        json_key="horizontal_launch_angle_degrees",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="total_spin",
        name="Total Spin",
        native_unit_of_measurement=REVOLUTIONS_PER_MINUTE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        icon="mdi:rotate-right",
        json_key="total_spin_rpm",
        message_type="shot",
        precision=0,
    ),
    GolfDashboardSensorEntityDescription(
        key="spin_axis",
        name="Spin Axis",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        icon="mdi:axis-arrow",
        json_key="spin_axis_degrees",
        message_type="shot",
        precision=0,
    ),
    GolfDashboardSensorEntityDescription(
        key="carry_distance",
        name="Carry Distance",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:flag-variant",
        json_key="carry_distance_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="total_distance",
        name="Total Distance",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:chart-line",
        json_key="total_distance_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="offline_distance",
        name="Offline Distance",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:target-variant",
        json_key="offline_distance_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="backspin",
        name="Backspin",
        native_unit_of_measurement=REVOLUTIONS_PER_MINUTE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        icon="mdi:rotate-right-variant",
        json_key="backspin_rpm",
        message_type="shot",
        precision=0,
    ),
    GolfDashboardSensorEntityDescription(
        key="sidespin",
        name="Sidespin",
        native_unit_of_measurement=REVOLUTIONS_PER_MINUTE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        icon="mdi:rotate-left-variant",
        json_key="sidespin_rpm",
        message_type="shot",
        precision=0,
    ),
    GolfDashboardSensorEntityDescription(
        key="club_speed",
        name="Club Speed",
        native_unit_of_measurement=UnitOfSpeed.METERS_PER_SECOND,
        device_class=SensorDeviceClass.SPEED,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:golf-tee",
        json_key="club_speed_meters_per_second",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="smash_factor",
        name="Smash Factor",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
        icon="mdi:chart-bell-curve-cumulative",
        json_key="smash_factor",
        message_type="shot",
        precision=2,
    ),
    GolfDashboardSensorEntityDescription(
        key="shot_type",
        name="Shot Type",
        icon="mdi:target-arrow",
        json_key="shot_name",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="shot_rank",
        name="Shot Rank",
        icon="mdi:medal-outline",
        json_key="shot_rank",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="shot_color",
        name="Shot Color",
        icon="mdi:palette",
        json_key="shot_color_rgb",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="tour_carry",
        name="NOVA Tour Carry",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:trophy",
        json_key="tour_carry_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="tour_total",
        name="NOVA Tour Total",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:trophy-outline",
        json_key="tour_total_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="carry_delta_to_tour",
        name="NOVA Carry vs Tour",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:compare",
        json_key="carry_delta_to_tour_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="shot_quality",
        name="NOVA Shot Quality",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        icon="mdi:star-circle",
        json_key="shot_quality_score",
        message_type="shot",
        precision=0,
    ),
    GolfDashboardSensorEntityDescription(
        key="launch_in_window",
        name="Launch In Window",
        icon="mdi:arrow-up-down",
        json_key="launch_in_window",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="spin_in_window",
        name="Spin In Window",
        icon="mdi:sync",
        json_key="spin_in_window",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="start_in_window",
        name="Start Line In Window",
        icon="mdi:arrow-left-right",
        json_key="start_in_window",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="optimal_window_summary",
        name="Optimal Window Summary",
        icon="mdi:check-decagram",
        json_key="optimal_window_label",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="club_recommendation",
        name="Club Recommendation",
        icon="mdi:golf",
        json_key="club_recommendation",
        message_type="shot",
    ),
    GolfDashboardSensorEntityDescription(
        key="amateur_carry",
        name="Amateur Carry Benchmark",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:account",
        json_key="amateur_carry_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="amateur_total",
        name="Amateur Total Benchmark",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:account-outline",
        json_key="amateur_total_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="lpga_carry",
        name="LPGA Carry Benchmark",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:human-female",
        json_key="lpga_carry_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="lpga_total",
        name="LPGA Total Benchmark",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:human-female-female",
        json_key="lpga_total_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="carry_delta_to_amateur",
        name="Carry vs Amateur",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:compare-horizontal",
        json_key="carry_delta_to_amateur_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="carry_delta_to_lpga",
        name="Carry vs LPGA",
        native_unit_of_measurement=UnitOfLength.YARDS,
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:compare-horizontal",
        json_key="carry_delta_to_lpga_yards",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="spin_loft",
        name="NOVA Spin Loft",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:angle-acute",
        json_key="spin_loft_deg",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="attack_angle",
        name="NOVA Attack Angle",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:arrow-down-bold",
        json_key="attack_angle_deg",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="face_angle",
        name="NOVA Face Angle",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:face-recognition",
        json_key="face_angle_deg",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="face_to_path",
        name="NOVA Face to Path",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:axis-arrow",
        json_key="face_to_path_deg",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="club_path",
        name="NOVA Club Path",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:axis-arrow-lock",
        json_key="club_path_deg",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="apex_height",
        name="NOVA Apex Height",
        native_unit_of_measurement=UnitOfLength.FEET,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:arrow-up-bold",
        json_key="apex_height_feet",
        message_type="shot",
        precision=1,
    ),
    GolfDashboardSensorEntityDescription(
        key="hang_time",
        name="NOVA Hang Time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
        icon="mdi:timer-outline",
        json_key="hang_time_seconds",
        message_type="shot",
        precision=2,
    ),
    GolfDashboardSensorEntityDescription(
        key="descent_angle",
        name="NOVA Descent Angle",
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        icon="mdi:arrow-down-bold-hexagon-outline",
        json_key="descent_angle_deg",
        message_type="shot",
        precision=1,
    ),
)

# Status Sensors (from "type": "status" messages)
STATUS_SENSORS: tuple[GolfDashboardSensorEntityDescription, ...] = (
    GolfDashboardSensorEntityDescription(
        key="uptime",
        name="Uptime",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=0,
        icon="mdi:timer-outline",
        json_key="uptime_seconds",
        message_type="status",
        precision=0,
    ),
)

ALL_SENSORS = SHOT_SENSORS + STATUS_SENSORS
